### ISSUE TITLE
Set up development tools

### ISSUE THREAD

**Issue by webknjaz** [wk-tech/python-smsfly#5]
- [x] `pre-commit`. Here's an example of `.pre-commit-config.yaml`

``` yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: master
  hooks:
  - id: trailing-whitespace
    exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
  - id: check-merge-conflict
    exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
  - id: double-quote-string-fixer
    exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
  - id: end-of-file-fixer
    exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
  # - id: fix-encoding-pragma
  #   exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
  - id: check-xml
    exclude: wargaming|bigworld|saber/(tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
  - id: name-tests-test
    exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
  - id: flake8
    exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$|Transport/Generated)|surrogates))
  - id: debug-statements
    exclude: wargaming|bigworld|saber/(server|template|tools|transport|scripts/(common/(TemplateData|pydev|bwpydevd.py$)|surrogates))
```
- [ ] `vagga`
- [ ] maybe `tox` to test code against several python versions
